"""initial schema

Revision ID: d8f0255f89fd
Revises: 
Create Date: 2025-12-15 05:26:05.079095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f0255f89fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=75), nullable=True),
    sa.Column('sobreNome', sa.String(length=75), nullable=True),
    sa.Column('nome_completo', sa.String(length=150), nullable=True),
    sa.Column('Telefone', sa.String(length=13), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('senha', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome_completo')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(length=150), nullable=True),
    sa.Column('Nome_abreviado', sa.String(length=75), nullable=True),
    sa.Column('Img_link', sa.String(), nullable=True),
    sa.Column('Funcao', sa.String(), nullable=True),
    sa.Column('Caracteristicas', sa.String(), nullable=True),
    sa.Column('Cores_disponiveis', sa.String(), nullable=True),
    sa.Column('coresDiferentes', sa.Boolean(), nullable=True),
    sa.Column('Marca', sa.String(length=50), nullable=True),
    sa.Column('Tamanho', sa.String(), nullable=True),
    sa.Column('Quantidade', sa.Integer(), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Nome')
    )
    op.create_table('assinatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cores', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['cadastro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assinatura')
    op.drop_table('produtos')
    op.drop_table('cadastro')
    # ### end Alembic commands ###
